import { SubtitleAPIV1, Subtitle } from './subtitle-types';

export class SubtitleAdapter {
  static toLegacySubtitle(apiSubtitle: SubtitleAPIV1): Subtitle {
    const attributes = apiSubtitle.attributes;
    const firstFile = attributes.files[0] || {};
    
    return {
      MatchedBy: "imdb",
      IDSubMovieFile: String(firstFile.file_id || ''),
      MovieHash: "",
      MovieByteSize: "",
      MovieTimeMS: "",
      IDSubtitleFile: attributes.subtitle_id,
      SubFileName: firstFile.file_name || "",
      SubActualCD: String(firstFile.cd_number || 1),
      SubSize: "",
      SubHash: "",
      SubLastTS: "",
      SubTSGroup: null,
      InfoReleaseGroup: null,
      InfoFormat: null,
      InfoOther: null,
      IDSubtitle: attributes.subtitle_id,
      UserID: String(attributes.uploader?.uploader_id || ''),
      SubLanguageID: attributes.language,
      SubFormat: "srt",
      SubSumCD: String(attributes.files.length || 1),
      SubAuthorComment: attributes.comments || '',
      SubAddDate: attributes.upload_date,
      SubBad: "0",
      SubRating: String(attributes.ratings || 0),
      SubSumVotes: String(attributes.votes || 0),
      SubDownloadsCnt: String(attributes.download_count || 0),
      MovieReleaseName: attributes.release || '',
      MovieFPS: String(attributes.fps || 0),
      IDMovie: String(attributes.feature_details?.feature_id || ''),
      IDMovieImdb: String(attributes.feature_details?.imdb_id || ''),
      MovieName: attributes.feature_details?.movie_name || '',
      MovieNameEng: attributes.feature_details?.title || '',
      MovieYear: String(attributes.feature_details?.year || ''),
      MovieImdbRating: "",
      SubFeatured: "0",
      UserNickName: attributes.uploader?.name || '',
      SubTranslator: "",
      ISO639: attributes.language,
      LanguageName: attributes.language,
      SubComments: attributes.comments || '',
      SubHearingImpaired: attributes.hearing_impaired ? "1" : "0",
      UserRank: attributes.uploader?.rank || '',
      SeriesSeason: "",
      SeriesEpisode: "",
      MovieKind: attributes.feature_details?.feature_type.toLowerCase() || 'movie',
      SubHD: attributes.hd ? "1" : "0",
      SeriesIMDBParent: "",
      SubEncoding: "UTF-8",
      SubAutoTranslation: attributes.ai_translated ? "1" : "0",
      SubForeignPartsOnly: attributes.foreign_parts_only ? "1" : "0",
      SubFromTrusted: attributes.from_trusted ? "1" : "0",
      QueryCached: 1,
      SubTSGroupHash: null,
      SubDownloadLink: `file_${firstFile.file_id}`,
      ZipDownloadLink: "",
      SubtitlesLink: attributes.url,
      Score: attributes.points || 0,
    };
  }
}